group = io.github.harezmi
version = 0.1.7
#test
javaToolchainVersion=25
javaBytecodeVersion=17
kotlinPluginVersion=2.3.21
springBootVersion=4.1.0
springGrpcVersion=1.1.0
grpcVersion=1.81.0
grpcKotlinStubVersion=1.5.0
kotlinVersion=2.3.21
mockkVersion=1.14.11
protobufJavaVersion=3.25.5
dynamoDBLocalVersion=2.6.1
redisVersion=5.2.0
