javaToolchainVersion=25
javaBytecodeVersion=17
kotlinPluginVersion=2.3.21
springBootVersion=4.1.0
protobufJavaVersion=3.25.5
redisVersion=5.2.0
dynamodbVersion=1.12.717
grpcVersion=1.81.0
grpcKotlinStubVersion=1.5.0
<!--fit4jVersion-->
fit4jVersion=0.1.7
<!--/fit4jVersion-->
kotlin.daemon.jvmargs=-Xmx2g
